### ISSUE TITLE
crates extern order in examples

### ISSUE THREAD

**Issue by deszip** [gifnksm/oauth-client-rs#1]
Hi, 
it seems you have to first extern oauth itself and then curl. In example code you first extern curl.
I'm new to rust so maybe it's my mistake but it works only when oauth goes first.

**Comment by gifnksm** [comment]
`extern crate foo;` means "importing external crate `foo`" (see [rust book](http://doc.rust-lang.org/book/crates-and-modules.html#importing-external-crates)).

The order of `extern crate` declarations does not change meaning of the program.
So, you can write `oauth` on the first line, but the original example code is also valid rust program.
