### ISSUE TITLE
Request Verification Support

### ISSUE THREAD

**Issue by nick-benoit14** [gifnksm/oauth-client-rs#29]
There doesn't currently appear to be a rust implementation of oauth1 request verification. Basically this entails resigning the request and ensuring that the signature matches the provided signature. Would you be willing to accept a PR for this sort of functionality? I would love to add to this already existing project instead of cluttering the ecosystem with yet another oauth library. 

Thanks for your good work, 
Nick

**Comment by gifnksm** [comment]
Thank you for suggesting a new feature.
If you send such a Pull Request, I will happily merge it!

**Comment by gifnksm** [comment]
Fixed by #44
