### ISSUE TITLE
Does not build with openssl 1.1.1

### ISSUE THREAD

**Issue by jonhoo** [gifnksm/oauth-client-rs#37]
`oauth-client` currently depends on `reqwest 0.8`, which depends on `hyper-tls 0.1`, which again depends on `native-tls 0.1`, which pulls in `openssl 0.9.24`, which doesn't build with the most recent version of openssl (sfackler/rust-openssl#994). There are a few open PRs (#34 and #35) that bump the version of `reqwest` to `0.9`, which doesn't have this problem, so merging one of them might be the right way to move forward! Until then, we're sadly locked in a situation where the crate doesn't build :'(

**Comment by kallisti5** [comment]
@gifnksm Any chance you can merge @jonhoo 's pull requests? This Crate seems abandoned.
@jonhoo any interest in forking :-)

**Comment by kallisti5** [comment]
PR #36 seems like a great one that adds futures and fixes this issue as well.

**Comment by mcarpenter** [comment]
Ubuntu 18 furnishes OpenSSL 1.1.1 so also runs afoul of this issue.

Here is a workaround to compile against OpenSSL 1.0.2 until a new release is made:

``` bash
cd /tmp
wget https://www.openssl.org/source/openssl-1.0.2u.tar.gz
tar xf openssl-1.0.2u.tar.gz
cd openssl-1.0.2u
mkdir ~/openssl-1.0.2u
./Configure --prefix=~/openssl-1.0.2u linux-generic64
make -j8 
make install
~/openssl-1.0.2u/bin/openssl version # check okay

cd ~/my-rust-project
export OPENSSL_INCLUDE_DIR=~/openssl-1.0.2u/include
export OPENSSL_LIB_DIR=~/openssl-1.0.2u/lib
cargo build

SSL_CERT_DIR=/etc/ssl/certs ./target/debug/my-rust-project # else will look in ~/openssl-1.0.2u/ssl/cert.pem

```

**Comment by gifnksm** [comment]
I'm sorry for begin late.
`reqwest` is upgraded to 0.10 via #39, so this issue should be fixed.

If you have any problem with `oauth-client-rs` v0.4.1, please reopen this issue or file a new issue.
